"""Structured final-INI parsing and stable functional ordering."""

from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Dict, Iterable, List, Sequence, Tuple


_HEADER_RE = re.compile(r"^\s*\[([^\]]+)\]\s*$")
_WWMI_AUTOGEN_START_RE = re.compile(
    r"^\s*;\s*Autogenerated\s*-+\s*$", re.I)
_WWMI_AUTOGEN_TEXT_RE = re.compile(
    r"^\s*;\s*This mod\.ini was generated by WWMI Tools\b", re.I)
_WWMI_AUTOGEN_END_RE = re.compile(
    r"^\s*;\s*AGMG Modding Community Discord\s*:", re.I)
_SLOT_BORDER_RE = re.compile(r"^\s*;\s*=+\s*$")
_SLOT_TITLE_RE = re.compile(r"^\s*;\s*Slot-style texture layer\b", re.I)
_SLOT_FORMS_RE = re.compile(r"^(\s*;\s*Forms\s*:\s*)(.*?)\s*$", re.I)
_DIRECT_THIS_RE = re.compile(
    r"^\s*this\s*=\s*([A-Za-z_][A-Za-z0-9_.-]*)\s*(?:;.*)?$", re.I)
_FILENAME_RE = re.compile(r"^\s*filename\s*=\s*\S.*$", re.I)


class IniDocumentError(ValueError):
    """Raised when a generated INI cannot be represented safely."""


@dataclass(frozen=True)
class IniSection:
    name: str
    prefix: Tuple[str, ...]
    body: Tuple[str, ...]
    ordinal: int


@dataclass(frozen=True)
class IniDocument:
    preamble: Tuple[str, ...]
    sections: Tuple[IniSection, ...]


def _merge_slot_boilerplate(
        blocks: Sequence[Sequence[str]]) -> Tuple[str, ...]:
    if not blocks:
        return ()
    forms: List[str] = []
    seen = set()
    for block in blocks:
        for line in block:
            match = _SLOT_FORMS_RE.match(line)
            if not match:
                continue
            for value in match.group(2).split(","):
                form = value.strip()
                key = form.casefold()
                if form and key not in seen:
                    seen.add(key)
                    forms.append(form)

    merged = list(blocks[0])
    if forms:
        for index, line in enumerate(merged):
            match = _SLOT_FORMS_RE.match(line)
            if match:
                merged[index] = match.group(1) + ", ".join(forms)
                break
    return tuple(merged)


def _extract_known_boilerplate(
        text: str) -> Tuple[str, Tuple[str, ...], Tuple[str, ...]]:
    """Extract repeated child-export comments without touching INI bodies."""

    lines = text.splitlines()
    removed = set()
    metadata_blocks: List[Tuple[str, ...]] = []
    slot_blocks: List[Tuple[str, ...]] = []

    index = 0
    while index < len(lines):
        if not _WWMI_AUTOGEN_START_RE.match(lines[index]):
            index += 1
            continue
        generated = False
        end = None
        for candidate in range(index + 1, min(len(lines), index + 40)):
            if _HEADER_RE.match(lines[candidate]):
                break
            generated = generated or bool(
                _WWMI_AUTOGEN_TEXT_RE.match(lines[candidate]))
            if _WWMI_AUTOGEN_END_RE.match(lines[candidate]):
                end = candidate
                break
        if generated and end is not None:
            metadata_blocks.append(tuple(lines[index:end + 1]))
            removed.update(range(index, end + 1))
            index = end + 1
            continue
        index += 1

    index = 0
    while index + 1 < len(lines):
        if (not _SLOT_BORDER_RE.match(lines[index])
                or not _SLOT_TITLE_RE.match(lines[index + 1])):
            index += 1
            continue
        end = None
        for candidate in range(index + 2, len(lines)):
            if _HEADER_RE.match(lines[candidate]):
                break
            if _SLOT_BORDER_RE.match(lines[candidate]):
                end = candidate
                break
        if end is not None:
            slot_blocks.append(tuple(lines[index:end + 1]))
            removed.update(range(index, end + 1))
            index = end + 1
            continue
        index += 1

    cleaned = "\n".join(
        line for line_index, line in enumerate(lines)
        if line_index not in removed)
    if text.endswith(("\n", "\r")):
        cleaned += "\n"
    metadata = metadata_blocks[0] if metadata_blocks else ()
    return cleaned, metadata, _merge_slot_boilerplate(slot_blocks)


def _is_leading_trivia(line: str) -> bool:
    stripped = line.strip()
    return not stripped or stripped.startswith(";")


def _next_prefix_start(lines: Sequence[str], previous_header: int, header: int) -> int:
    """Return a safe prefix boundary for an inter-section comment block."""

    region_start = previous_header + 1
    substantive = [
        index
        for index in range(region_start, header)
        if not _is_leading_trivia(lines[index])
    ]
    if not substantive:
        for separator in range(region_start, header):
            if lines[separator].strip():
                continue
            prefix_start = separator + 1
            while prefix_start < header and not lines[prefix_start].strip():
                prefix_start += 1
            if prefix_start < header:
                return prefix_start
        return header

    for separator in range(substantive[-1] + 1, header):
        if lines[separator].strip():
            continue
        prefix_start = separator + 1
        while prefix_start < header and not lines[prefix_start].strip():
            prefix_start += 1
        if prefix_start < header:
            return prefix_start
        return header
    return header


def parse_ini_document(text: str) -> IniDocument:
    """Parse sections while attaching explicitly separated prefixes safely."""

    lines = text.splitlines()
    headers = []
    for index, line in enumerate(lines):
        match = _HEADER_RE.match(line)
        if match:
            headers.append((index, match.group(1)))
    if not headers:
        raise IniDocumentError("generated INI has no sections")

    lowered = {}
    for _index, name in headers:
        key = name.casefold()
        if key in lowered:
            raise IniDocumentError(
                f"duplicate section header (case-insensitive): [{lowered[key]}] / [{name}]"
            )
        lowered[key] = name

    prefix_starts: List[int] = []
    for pos, (header_index, _name) in enumerate(headers):
        if pos == 0:
            prefix_starts.append(header_index)
            continue
        prefix_starts.append(
            _next_prefix_start(lines, headers[pos - 1][0], header_index)
        )

    preamble = tuple(lines[:prefix_starts[0]])
    sections: List[IniSection] = []
    for pos, (header_index, name) in enumerate(headers):
        next_prefix = prefix_starts[pos + 1] if pos + 1 < len(headers) else len(lines)
        prefix = tuple(lines[prefix_starts[pos]:header_index])
        body = tuple(lines[header_index + 1:next_prefix])
        sections.append(IniSection(name=name, prefix=prefix, body=body, ordinal=pos))
    return IniDocument(preamble=preamble, sections=tuple(sections))


def _category(section: IniSection) -> int:
    name = section.name.casefold()
    if name == "constants":
        return 0
    if name == "present":
        return 1
    if name.startswith(("textureoverride", "shaderoverride", "shaderregex")):
        return 2
    if name.startswith("commandlistdrawcomponent"):
        return 3
    if name.startswith("commandlistdrawgeometrycomponent"):
        return 4
    if name.startswith((
            "commandlistsettexturescomponent",
            "commandlistbackuppixelshaderresources",
            "commandlisttriggerresourceoverrides",
            "commandlistcleanupsharedresources",
            "commandlistrestorepixelshaderresources")):
        return 5
    if name.startswith("commandlist"):
        return 6
    if name.startswith(("resourcetexture", "resource_texture_")):
        return 7
    if name.startswith(("resource", "customshader")):
        return 8
    return 9


_BANNERS = {
    2: "; ===== Velo INI: Match overrides and paired hash textures =====",
    3: "; ===== Velo INI: Draw transactions =====",
    4: "; ===== Velo INI: Shared draw geometry =====",
    5: "; ===== Velo INI: Slot and PS-resource lifecycle =====",
    6: "; ===== Velo INI: Runtime command lists =====",
    7: "; ===== Velo INI: Texture resources =====",
    8: "; ===== Velo INI: Mesh and runtime resources =====",
    9: "; ===== Velo INI: Other sections =====",
}


def _paired_texture_resources(
        sections: Sequence[IniSection]) -> Dict[int, IniSection]:
    by_name = {section.name.casefold(): section for section in sections}
    resource_users: Dict[int, set] = {}
    candidates: Dict[int, IniSection] = {}

    for override in sections:
        if not override.name.casefold().startswith("textureoverride"):
            continue
        assignments = [
            match.group(1).casefold()
            for line in override.body
            if (match := _DIRECT_THIS_RE.match(line))
        ]
        referenced_resources = set()
        for target in assignments:
            resource = by_name.get(target)
            if resource is None or _category(resource) != 7:
                continue
            referenced_resources.add(resource.ordinal)
        for resource_ordinal in referenced_resources:
            resource_users.setdefault(resource_ordinal, set()).add(
                override.ordinal)

        if len(assignments) != 1:
            continue
        resource = by_name.get(assignments[0])
        if resource is None or _category(resource) != 7:
            continue
        if sum(bool(_FILENAME_RE.match(line)) for line in resource.body) != 1:
            continue
        candidates[override.ordinal] = resource

    return {
        override_ordinal: resource
        for override_ordinal, resource in candidates.items()
        if len(resource_users.get(resource.ordinal, ())) == 1
    }


def _without_sorter_boundary_banners(document: IniDocument) -> IniDocument:
    """Remove only canonical sorter banners proven at category boundaries."""

    sections = list(document.sections)
    if not sections:
        return document

    pairs = _paired_texture_resources(sections)
    paired_resources = {resource.ordinal for resource in pairs.values()}
    presentation_categories = [
        2 if section.ordinal in paired_resources else _category(section)
        for section in sections
    ]
    preamble = list(document.preamble)

    first_banner = _BANNERS.get(presentation_categories[0])
    if first_banner is not None:
        matches = [
            index for index, line in enumerate(preamble)
            if line == first_banner
        ]
        if matches:
            marker = matches[-1]
            trailing = preamble[marker + 1:]
            if all(_is_leading_trivia(line) for line in trailing):
                section = sections[0]
                sections[0] = IniSection(
                    name=section.name,
                    prefix=tuple(trailing) + section.prefix,
                    body=section.body,
                    ordinal=section.ordinal,
                )
                preamble = preamble[:marker]

    for index in range(1, len(sections)):
        category = presentation_categories[index]
        if category == presentation_categories[index - 1]:
            continue
        banner = _BANNERS.get(category)
        if banner is None or banner not in sections[index].prefix:
            continue
        prefix = list(sections[index].prefix)
        prefix.remove(banner)
        section = sections[index]
        sections[index] = IniSection(
            name=section.name,
            prefix=tuple(prefix),
            body=section.body,
            ordinal=section.ordinal,
        )

    return IniDocument(preamble=tuple(preamble), sections=tuple(sections))


def _ordered_sections(
        sections: Sequence[IniSection]) -> List[Tuple[int, IniSection]]:
    pairs = _paired_texture_resources(sections)
    paired_resources = {resource.ordinal for resource in pairs.values()}
    ordered = sorted(
        (section for section in sections
         if section.ordinal not in paired_resources),
        key=lambda section: (_category(section), section.ordinal),
    )
    emitted: List[Tuple[int, IniSection]] = []
    for section in ordered:
        resource = pairs.get(section.ordinal)
        if resource is not None:
            emitted.append((2, resource))
        emitted.append((_category(section), section))
    return emitted


def _trim_boundary_blank_lines(lines: Iterable[str]) -> List[str]:
    out = list(lines)
    while out and not out[-1].strip():
        out.pop()
    return out


def _trim_blank_lines(lines: Iterable[str]) -> List[str]:
    out = _trim_boundary_blank_lines(lines)
    while out and not out[0].strip():
        out.pop(0)
    return out


def stable_functional_sort(text: str) -> str:
    """Return a deterministic category order without reordering match sections."""

    cleaned, metadata, slot_boilerplate = _extract_known_boilerplate(text)
    document = parse_ini_document(cleaned)
    document = _without_sorter_boundary_banners(document)
    original_match_order = [
        section.name for section in document.sections if _category(section) == 2
    ]
    ordered = _ordered_sections(document.sections)
    if [
            section.name for _category_id, section in ordered
            if _category(section) == 2
    ] != original_match_order:
        raise IniDocumentError("match-bearing section order changed")

    out = _trim_boundary_blank_lines(document.preamble)
    if metadata:
        if out:
            out.extend(["", ""])
        out.extend(_trim_blank_lines(metadata))
    if out:
        out.extend(["", ""])
    last_category = None
    slot_boilerplate_emitted = False
    for category, section in ordered:
        if category != last_category and category in _BANNERS:
            if out and out[-1].strip():
                out.append("")
            out.extend([_BANNERS[category], ""])
            if category == 5 and slot_boilerplate:
                out.extend(_trim_blank_lines(slot_boilerplate))
                out.append("")
                slot_boilerplate_emitted = True
        prefix = _trim_blank_lines(section.prefix)
        if prefix:
            out.extend(prefix)
        out.append(f"[{section.name}]")
        out.extend(section.body)
        while out and not out[-1].strip():
            out.pop()
        out.extend(["", ""])
        last_category = category
    if slot_boilerplate and not slot_boilerplate_emitted:
        out.extend(_trim_blank_lines(slot_boilerplate))
    return "\n".join(_trim_boundary_blank_lines(out)) + "\n"
